nextjs template
nix-community/templates pull request #5
Opened 2023-09-29 04:25 UTC by ivandimitrov8080

a nextjs template with a dev shell and default build

2023-09-29 17:32 UTC, IogaMaster commented
Thanks for contibuting! Would there be a way to get most of the hash info from the package-lock.json. The same way it's done in the Rust template with the Cargo.lock?
https://github.com/nix-community/templates/blob/c873911833b3e635ef11137ad9b7f42ea92b0b85/rust/flake.nix#L34

2023-09-29 17:38 UTC, IogaMaster requested changes

2023-09-29 17:38 UTC, IogaMaster commented on nextjs/flake.nix
> +        devShell = pkgs.mkShell {
```suggestion
        devShells.default = pkgs.mkShell {
```

2023-09-29 17:38 UTC, IogaMaster commented on nextjs/flake.nix
> +        devShell = pkgs.mkShell {
To fix flake error

2023-09-29 17:38 UTC, IogaMaster commented on nextjs/flake.nix
> +  description = ''
Instead of describing what to do here. Add it to a welcome text in the root flake.nix

2023-09-29 17:39 UTC, IogaMaster commented on nextjs/flake.nix
> +  description = ''
Like how its done here:

https://github.com/nix-community/templates/blob/c873911833b3e635ef11137ad9b7f42ea92b0b85/flake.nix#L20C1-L29

2023-10-01 14:31 UTC, ivandimitrov8080 commented
> Thanks for contibuting! Would there be a way to get most of the hash info from the package-lock.json. The same way it's done in the Rust template with the Cargo.lock?
> 
> https://github.com/nix-community/templates/blob/c873911833b3e635ef11137ad9b7f42ea92b0b85/rust/flake.nix#L34-L36

Unfortunately, I don't see how it can be done if possible. In [the documentation](https://nixos.org/manual/nixpkgs/stable/#javascript-tool-specific) it says to use `prefetch-npm-deps`, which works fine.

2023-10-01 16:07 UTC, IogaMaster commented
Okay, I'll look into a solution. Thanks for your help!

2023-10-01 16:07 UTC, merged